# Generated by Django 3.2.6 on 2022-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('operation', models.CharField(choices=[('ssh', 'Open-SSH'), ('check', 'Check-me'), ('logs', 'client-logs'), ('ddos', 'DDOS'), ('domain', 'Domain'), ('available', 'Check-available')], max_length=9)),
                ('system', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteIP',
            fields=[
                ('ip', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('countries', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
