# Generated by Django 3.2.6 on 2022-04-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whiteip',
            old_name='countries',
            new_name='country',
        ),
    ]
