# Generated by Django 3.0.2 on 2020-01-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('ip', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ip address')),
                ('user_agent', models.CharField(max_length=100, verbose_name='user agen ')),
            ],
        ),
    ]
