# Generated by Django 3.0.2 on 2020-02-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='FinishTime',
            field=models.DateTimeField(auto_now=True, db_column='finish_time'),
        ),
    ]
